language: python
python: 3.8
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_a92c2badb3e4_key -iv $encrypted_a92c2badb3e4_iv -in .travis/secret.tar.enc -out secret.tar -d
- tar xvf secret.tar
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.3/bin/linux/amd64/kubectl
  && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
script:
- make build
deploy:
  provider: script
  script:
  - make release
  - KUBECONFIG=./kubeconfig make deploy
  on:
    branch: master
env:
  global:
    secure: V2aS0sLgXhw9up4c5QQvPxE/KBD6NU/5hZw/nhQHLU6Cv/E+/whIhk9Swi61gZpY0SqU5RiEkLKkjLytrKvX2wTCKPLl6KrxWBxtB+ALGJGyBVBuJ89velz3CeZzkIozrV8EE0zAiGig+M4WUXfrTMRmnBO9pHdAzDvbgVT17D8jiScYIMkEJ2iSdBM89FwhT/AGZtAwMYumlcFv6d7PiNA63ECDlzp7c16IWgHWCNIHt7ZlqLbLbPfY16uOhSuJOJ0/u6GPrI/+U5YC7PhEWxkZzQ60Tj4ZjFs1EtEzApqb5tnHBlknmhd5RFGf8rc6OrOEQJebulzxoawO4F9liiifb+2jYjN67kyxq61j6NEqeobfaBKARkCvhQ5YmaS3OPh273D5eCFnj5+IyyRQUQYDo9mOGWf6e9IinV52dl/+08PO2HTwM9ECO03N5TdP3wftv8NWnuHf5FuPrt1TY1x8FksyVC0WU3IM9ge2wPSxCGAtOWV27hqAxlpyKyky+hZIbFJ/cZ4lJAtn2I0FE1QdtzlcopjSViGLXd+H9Xgi7mj7zwbtQSG+Rvof3X1orUFXpSmMbVKF+xwQYkb83t0QIQF4T22L31xaW8u8ewHi04MO7nNQ3TmijsCPfWgGTDB2F3HWUFO941GGLAEFK+A+62yKqwL1fF3qT3PXq8c=
