name: cd

on:
  pull_request:
    branches:
      - 'master'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v5.0.0
      with:
        images: |
          ghcr.io/sorend/ad-py
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.2.0
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        file: Dockerfile
